### ISSUE TITLE
在快速切换fragment的时候，出现了异常

### ISSUE THREAD

**Issue by Mr-jinPH** [hegaojian/JetpackMvvm#89]
2021-09-05 09:57:34.427 6320-6320/com.android.car.ly_settings E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.car.ly_settings, PID: 6320
    java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:328)
        at com.kunminx.architecture.ui.callback.ProtectedUnPeekLiveData.observeInFragment(ProtectedUnPeekLiveData.java:66)
        at com.szlanyou.os.basic_common.base.fragment.BaseVmFragment.onVisible$lambda-1(BaseVmFragment.kt:104)
        at com.szlanyou.os.basic_common.base.fragment.BaseVmFragment.lambda$LNbKNJpOrduWMSYgwdl9DgBWY2M(Unknown Source:0)
        at com.szlanyou.os.basic_common.base.fragment.-$$Lambda$BaseVmFragment$LNbKNJpOrduWMSYgwdl9DgBWY2M.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1268)
    
    
    --------- beginning of system

**Comment by JasonLinkinBright** [comment]
遇到了同样的问题，请问怎么解决
