### ISSUE TITLE
第三方下载报错

### ISSUE THREAD

**Issue by salecoding** [hegaojian/JetpackMvvm#98]
java.lang.VerifyError: Verifier rejected class me.hgj.jetpackmvvm.ext.download.FileTool: java.lang.Object me.hgj.jetpackmvvm.ext.download.FileTool.downToFile(java.lang.String, java.lang.String, java.lang.String, long, okhttp3.ResponseBody, me.hgj.jetpackmvvm.ext.download.OnDownLoadListener, kotlin.coroutines.Continuation) failed to verify: java.lang.Object me.hgj.jetpackmvvm.ext.download.FileTool.downToFile(java.lang.String, java.lang.String, java.lang.String, long, okhttp3.ResponseBody, me.hgj.jetpackmvvm.ext.download.OnDownLoadListener, kotlin.coroutines.Continuation): [0x17A] register v2 has type Reference: java.lang.Throwable but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef (declaration of 'me.hgj.jetpackmvvm.ext.download.FileTool' appears in /data/app/~~iXQFAkPYpdkXohp1Von84w==/me.hgj.jetpackmvvm.demo-CLKAixzFW7s6pbPZ9bJkiQ==/base.apk!classes4.dex)
        at me.hgj.jetpackmvvm.demo.ui.fragment.demo.DownLoadLibraryFragment$ProxyClick.downloadLibrary(DownLoadLibraryFragment.kt:77)
        at me.hgj.jetpackmvvm.demo.databinding.FragmentDownloadLibraryBindingImpl._internalCallbackOnClick(FragmentDownloadLibraryBindingImpl.java:157)
        at me.hgj.jetpackmvvm.demo.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:8160)
        at android.widget.TextView.performClick(TextView.java:16222)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30236)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2022-01-10 20:07:59.351 22699-22699/me.hgj.jetpackmvvm.demo E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.VerifyError: Verifier rejected class me.hgj.jetpackmvvm.ext.download.FileTool: java.lang.Object me.hgj.jetpackmvvm.ext.download.FileTool.downToFile(java.lang.String, java.lang.String, java.lang.String, long, okhttp3.ResponseBody, me.hgj.jetpackmvvm.ext.download.OnDownLoadListener, kotlin.coroutines.Continuation) failed to verify: java.lang.Object me.hgj.jetpackmvvm.ext.download.FileTool.downToFile(java.lang.String, java.lang.String, java.lang.String, long, okhttp3.ResponseBody, me.hgj.jetpackmvvm.ext.download.OnDownLoadListener, kotlin.coroutines.Continuation): [0x17A] register v2 has type Reference: java.lang.Throwable but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef (declaration of 'me.hgj.jetpackmvvm.ext.download.FileTool' appears in /data/app/~~iXQFAkPYpdkXohp1Von84w==/me.hgj.jetpackmvvm.demo-CLKAixzFW7s6pbPZ9bJkiQ==/base.apk!classes4.dex)
        at me.hgj.jetpackmvvm.demo.ui.fragment.demo.DownLoadLibraryFragment$ProxyClick.downloadLibrary(DownLoadLibraryFragment.kt:77)
        at me.hgj.jetpackmvvm.demo.databinding.FragmentDownloadLibraryBindingImpl._internalCallbackOnClick(FragmentDownloadLibraryBindingImpl.java:157)
        at me.hgj.jetpackmvvm.demo.generated.callback.OnClickListener.onClick(OnClickListener.java:11)
        at android.view.View.performClick(View.java:8160)
        at android.widget.TextView.performClick(TextView.java:16222)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30236)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by hegaojian** [comment]
下载已经去除不维护了
